In [4]:
import pandas as pd
import numpy as np


In [6]:
pd.__version__

'2.2.2'

In [7]:
df = pd.read_csv('car_fuel_efficiency.csv')

In [10]:
df.shape

(9704, 11)

In [11]:
df.head()

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                  170            3.0       159.0     3413.433759   
1                  130            5.0        97.0     3149.664934   
2                  170            NaN        78.0     3079.038997   
3                  220            4.0         NaN     2542.392402   
4                  210            1.0       140.0     3460.870990   

   acceleration  model_year  origin fuel_type         drivetrain  num_doors  \
0          17.7        2003  Europe  Gasoline    All-wheel drive        0.0   
1          17.8        2007     USA  Gasoline  Front-wheel drive        0.0   
2          15.1        2018  Europe  Gasoline  Front-wheel drive        0.0   
3          20.2        2009     USA    Diesel    All-wheel drive        2.0   
4          14.4        2009  Europe  Gasoline    All-wheel drive        2.0   

   fuel_efficiency_mpg  
0            13.231729  
1            13.688217  
2            14.246341  
3            16.912736  
4            12.488369

In [20]:
fuel_type =df.fuel_type
fuel_type.nunique()

2

In [25]:
df.isnull().sum()



engine_displacement      0
num_cylinders          482
horsepower             708
vehicle_weight           0
acceleration           930
model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors              502
fuel_efficiency_mpg      0
dtype: int64

In [38]:
asia_cars = df[(df.origin=='Asia')]
asia_cars.fuel_efficiency_mpg.max()

23.759122836520497

In [41]:
median_horsepower=df.horsepower.median()
median_horsepower

149.0

In [44]:
median_horsepower_mode = df.horsepower.mode()
median_horsepower_mode

0    152.0
Name: horsepower, dtype: float64

In [48]:
df.horsepower = df['horsepower'].fillna(median_horsepower_mode[0])
df.horsepower.isnull().sum()


0

In [50]:
df.horsepower.median()

152.0

In [51]:
asia_cars = df[(df.origin=='Asia')]
asia_cars_filtered = asia_cars[['vehicle_weight','model_year']]

In [53]:
asia_cars_filtered_seven=asia_cars_filtered.head(7)

In [54]:
asia_cars_filtered_seven

vehicle_weight  model_year
8      2714.219310        2016
12     2783.868974        2010
14     3582.687368        2007
20     2231.808142        2011
21     2659.431451        2016
34     2844.227534        2014
38     3761.994038        2019

In [57]:
x = asia_cars_filtered_seven.values
x

array([[2714.21930965, 2016.        ],
       [2783.86897424, 2010.        ],
       [3582.68736772, 2007.        ],
       [2231.8081416 , 2011.        ],
       [2659.43145076, 2016.        ],
       [2844.22753389, 2014.        ],
       [3761.99403819, 2019.        ]])

In [60]:
x_transp = np.transpose(x)
x_transp

array([[2714.21930965, 2783.86897424, 3582.68736772, 2231.8081416 ,
        2659.43145076, 2844.22753389, 3761.99403819],
       [2016.        , 2010.        , 2007.        , 2011.        ,
        2016.        , 2014.        , 2019.        ]])

In [64]:
XTX = x_transp @ x
XTX

array([[62248334.33150762, 41431216.50732678],
       [41431216.50732678, 28373339.        ]])

In [68]:
import numpy as np

XTX_inv = np.linalg.inv(XTX)
XTX_inv


array([[ 5.71497081e-07, -8.34509443e-07],
       [-8.34509443e-07,  1.25380877e-06]])

In [58]:
y = [1100, 1300, 800, 900, 1000, 1100, 1200]
y

[1100, 1300, 800, 900, 1000, 1100, 1200]

In [72]:
z = XTX_inv @ x_transp
z

array([[-1.31202622e-04, -8.63909858e-05,  3.72634923e-04,
        -4.02726650e-04, -1.62513724e-04, -5.52342829e-05,
         4.65094049e-04],
       [ 2.62636846e-04,  1.96990690e-04, -4.73392228e-04,
         6.58944477e-04,  3.08357831e-04,  1.51636137e-04,
        -6.07979633e-04]])

In [75]:
w = z @ y
w

array([0.01386421, 0.5049067 ])

In [76]:
w.sum()

0.5187709081074007